"""Implements options for Solution Builder"""
from pdb_reader import PDBBrowserProcess
from input_generator import InputBrowserProcess

_BROWSER_PROCESS = 'SolutionBrowserProcess'

class SolutionBrowserProcess(PDBBrowserProcess, InputBrowserProcess):
    """Implements selection of solution settings"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.module_title = "Solution Builder"
        self.module_url = "?doc=input/solution"

    def set_ion_method(self):
        """Uses Monte-Carlo method unless ion_method[0] is d or D"""
        if not 'ion_method' in self.test_case:
            raise ValueError("Missing ion_method")

        if self.test_case.get('ion_type') == False:
            # this is probably an autogenerated test variation with ions disabled
            print(self.name, "warning: skipping ion method selection")
            return

        ion_method = str(self.test_case['ion_method']).lower()[0]
        ion_method = 'dist' if ion_method == 'd' else 'mc'

        self.browser.select('ion_method', ion_method)

    def set_ion_type(self):
        """Sets the type of ion to place in solution"""
        if not 'ion_type' in self.test_case:
            raise ValueError("Missing ion_type")

        # map ion type in case-insensitive manner
        ion_type = str(self.test_case['ion_type']).lower()
        ion_type = {
            'kcl': 'KCl',
            'nacl': 'NaCl',
            'mgcl2': 'MgCl2',
            'cacl2': 'CaCl2',
        }[ion_type]

        if ions_table := self.browser.find_by_id('ions_table'):
            remove_button = ions_table.find_by_css('input[onclick="remove_ion_row(this)"]')
            self.wait_exists(remove_button).click()
            self.browser.find_by_id('ion_type').select(ion_type)
            self.browser.evaluate_script('add_simple_ion_row()')
        else:
            self.browser.select('ion_type', ion_type)

    def set_xyz(self):
        """Sets box dimensions"""
        dims = 'xyz'
        boxtype_names = 'boxtype', 'solvtype'

        # user must set at least one dimension when calling this function
        found = False
        for dim in dims:
            if dim in self.test_case:
                # only process XYZ dimensions once
                if self.test_case[dim] == False:
                    return
                found = True
                break
            if dim.upper() in self.test_case:
                self.test_case[dim] = self.test_case.pop(dim.upper())
                found = True

        if not found:
            raise ValueError("Must specify at least one XYZ dimension")

        self.click_by_attrs(name="solvate_option", value="explicit")

        solvtype = 'rect'
        for name in boxtype_names:
            if name in self.test_case:
                solvtype = self.test_case[name][:4].lower()
                break

        name_tpl = "box[{}][{}]"
        for dim in dims:
            if dim in self.test_case:
                value = self.test_case[dim]
                dim = dim.lower()

                name = name_tpl.format(solvtype, dim)
                self.browser.fill(name, value)

                # prevents set_xyz() from doing anything more than once
                self.test_case[dim] = False
